language: python

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8

env:
  - APP_ID=8FfQwpvihLHK4htqmtEvkNrv
  - APP_KEY=eE9tNOcCiWoMHM1phxY41rAz
  - MASTER_KEY=75zAjEJSj7lifKQqKSTryae9
  - USE_REGION=US

sudo: false

install:
  - pip install -e .'[test]'
  - pip install codecov

script:
  - nosetests -v --with-coverage --cover-package=leancloud

after_success:
  - codecov

notifications:
  email: false
